export const ERROR_CODES = {
  EMPTY_UPDATE_PAYLOAD: 'EMPTY_UPDATE_PAYLOAD',
  INVALID_RELATION_REFERENCE: 'INVALID_RELATION_REFERENCE',

  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',
  MODULE_NAME_EXISTS: 'MODULE_NAME_EXISTS',
  MODULE_HAS_PERMISSIONS: 'MODULE_HAS_PERMISSIONS',

  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_NAME_EXISTS: 'ROLE_NAME_EXISTS',
  ROOT_ROLE_CANNOT_BE_DOWNGRADED: 'ROOT_ROLE_CANNOT_BE_DOWNGRADED',
  ROOT_ROLE_CANNOT_BE_DELETED: 'ROOT_ROLE_CANNOT_BE_DELETED',
  ROOT_ROLE_PERMISSIONS_IMPLICIT: 'ROOT_ROLE_PERMISSIONS_IMPLICIT',

  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',
  PERMISSION_ALREADY_EXISTS: 'PERMISSION_ALREADY_EXISTS',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  DUPLICATE_UNIQUE_VALUE: 'DUPLICATE_UNIQUE_VALUE',
  SELECTED_ROLE_NOT_FOUND: 'SELECTED_ROLE_NOT_FOUND',
  SYSTEM_ROOT_USER_DELETE_FORBIDDEN: 'SYSTEM_ROOT_USER_DELETE_FORBIDDEN',
  SELF_ROLE_ASSIGNMENT_FORBIDDEN: 'SELF_ROLE_ASSIGNMENT_FORBIDDEN',
  SELF_ROLE_MODIFICATION_FORBIDDEN: 'SELF_ROLE_MODIFICATION_FORBIDDEN',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  NO_SYSTEM_RIGHTS: 'NO_SYSTEM_RIGHTS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  AUDIT_LOGS_VIEW_FORBIDDEN: 'AUDIT_LOGS_VIEW_FORBIDDEN',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
